import type { ExcalidrawElement } from '@excalidraw/excalidraw/element/types'

interface Props { element: ExcalidrawElement | null; onUpdate: (patch: Partial<ExcalidrawElement>) => void }
const palette = ['#ffffff', '#eef1f3', '#aeb7c2', '#34383f', '#3b82f6', '#22a06b', '#f4c542', '#f28c28', '#e05252', '#8b5cf6']
export function PropertiesPanel({ element, onUpdate }: Props) {
  if (!element) return <aside className="right-panel empty-properties"><span className="property-icon">✦</span><h2>속성 패널</h2><p>캔버스에서 요소를 선택하면<br />세부 속성을 편집할 수 있습니다.</p></aside>
  const updateNumber = (key: 'x' | 'y' | 'width' | 'height' | 'strokeWidth' | 'fontSize', value: string) => onUpdate({ [key]: Number(value) })
  const currentFill = 'backgroundColor' in element ? element.backgroundColor : '#ffffff'
  const currentStroke = 'strokeColor' in element ? element.strokeColor : '#34383f'
  const currentText = 'text' in element ? element.text : ''
  return <aside className="right-panel"><div className="property-title"><div><span className="eyebrow">INSPECTOR</span><h2>속성</h2></div><span className="type-tag">{element.type}</span></div><label>표시 텍스트<input value={currentText} placeholder="텍스트 없음" onChange={(event) => 'text' in element && onUpdate({ text: event.target.value })} /></label><div className="field-row"><label>X 위치<input type="number" value={Math.round(element.x)} onChange={(e) => updateNumber('x', e.target.value)} /></label><label>Y 위치<input type="number" value={Math.round(element.y)} onChange={(e) => updateNumber('y', e.target.value)} /></label></div><div className="field-row"><label>너비<input type="number" value={Math.round(element.width)} onChange={(e) => updateNumber('width', e.target.value)} /></label><label>높이<input type="number" value={Math.round(element.height)} onChange={(e) => updateNumber('height', e.target.value)} /></label></div><div className="property-group"><span>배경색</span><div className="swatches">{palette.map((color) => <button key={color} title={color} className="swatch" style={{ backgroundColor: color }} onClick={() => onUpdate({ backgroundColor: color })} />)}<input aria-label="배경색 직접 선택" type="color" value={currentFill} onChange={(e) => onUpdate({ backgroundColor: e.target.value })} /></div></div><div className="property-group"><span>테두리색</span><div className="swatches">{palette.map((color) => <button key={color} title={color} className="swatch" style={{ backgroundColor: color }} onClick={() => onUpdate({ strokeColor: color })} />)}<input aria-label="테두리색 직접 선택" type="color" value={currentStroke} onChange={(e) => onUpdate({ strokeColor: e.target.value })} /></div></div><div className="field-row"><label>테두리 두께<input type="number" min="0" max="12" value={element.strokeWidth} onChange={(e) => updateNumber('strokeWidth', e.target.value)} /></label>{'fontSize' in element && <label>글자 크기<input type="number" value={element.fontSize} onChange={(e) => updateNumber('fontSize', e.target.value)} /></label>}</div><div className="property-group"><span>투명도</span><input className="range" type="range" min="0" max="100" value={element.opacity} onChange={(e) => onUpdate({ opacity: Number(e.target.value) })} /></div></aside>
}
